unit/address_mapping_test.c

@ydahhrk noticed a discrepancy between the example translations in
draft-anderson-v6ops-siit-eam-02 appendix B and the algorithm itself.
Turns out, the examples in the appendix were wrong. The appendix will
be fixed in a -03 version of the draft to be uploaded soon; this commit
brings the Jool unit test code in line with the -03 version.

Fix test of EAM 192.0.2.128/26 <-> 2001:db8:dddd::/64

---

mod/common/packet.c

Reduce the log level for packet drops due to inbound IPv4 packets having
UDP checksum 0 to debug. This is to avoid the kernel ring buffer and
console being flooded with mostly useless messages, drowning out more
interesting messages.
For what it's worth, my Jool test node with an IPv4 /24 routed to it has
accumulated over 2700 of these log lines in less than two days of uptime.
It's caused by normal internet background radiation (e.g., bots scanning
for open UDP services they can abuse to amplify volumetric DDoS attacks).

Debug log level for drops due to UDP w/checksum 0

---

doc/usr/misc-rfc6791.md

The IPv4-translatable IPv6 address in the table clearly encodes the IPv4
address in bits 96-127, while the text above says that the translation
prefix is a /64. One of them must therefore be incorrect. Quoting from
RFC6052 section 2.3:
```
o  When the prefix is 64 bits long, the IPv4 address is encoded in
positions 72 to 103.
o  When the prefix is 96 bits long, the IPv4 address is encoded in
positions 96 to 127.
```

Use /96 translation prefix instead of /64

---

.gitignore
INSTALL
dkms.conf
doc/usr/mod-install.md
include/nat64/common/nat64.h

Dynamic Kernel Module Support (DKMS) is a framework used by various
distributions to handle third-party kernel modules such as Jool. It
takes care of all the necessary steps in order to build and install
kernel modules (make, make modules_install, depmod), and will also
ensure these steps are automatically performed all over again
whenever the kernel packages are being upgraded. This is very
convenient in production scenarios, as it prevents the operator from
accidentally ending up with a non-functional Jool installation (due
to missing kernel modules) after installing any pending distribution
updates and subsequently rebooting.
Note: When creating release archives, the PACKAGE_VERSION variable
in dkms.conf should probably be manually updated to hard-code the
version string (i.e., the git …

Add support for the DKMS framework

---

mod/common/core.c
mod/common/namespace.c
mod/stateful/nf_hook.c
mod/stateless/nf_hook.c

Compile failed in Linux kernel 4.1.
```
$ make
make -C stateless
make[1]: Entering directory `/home/pandax381/LOCAL/NAT64/mod/stateless'
make -C /lib/modules/4.1.7-v7+/build M=$PWD JOOL_FLAGS=""
make[2]: Entering directory `/usr/src/linux-headers-4.1.7-v7+'
CC [M]  /home/pandax381/LOCAL/NAT64/mod/stateless/../common/rfc6145/4to6.o
CC [M]  /home/pandax381/LOCAL/NAT64/mod/stateless/../common/rfc6145/6to4.o
CC [M]  /home/pandax381/LOCAL/NAT64/mod/stateless/../common/rfc6145/common.o
CC [M]  /home/pandax381/LOCAL/NAT64/mod/stateless/../common/rfc6145/core.o
CC [M]  /home/pandax381/LOCAL/NAT64/mod/stateless/../common/address.o
CC [M]  /home/pandax381/LOCAL/NAT64/mod/stateless/../common/types.o
CC [M]  /home/pandax381/LOCAL/NAT64/mod/stateless/../common/str_utils.o
CC [M] …
```

support kernel 4.1 or later

---

en/install-usr.md

On a brand new Ubuntu 16.04.1 LTS xenial:
```
...
checking for pkg-config... no
checking for LIBNLGENL3... no
configure: error: in `/root/Jool-3.5.0/usr':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.
Alternatively, you may set the environment variables LIBNLGENL3_CFLAGS
and LIBNLGENL3_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
```
After I installed pkg-config (`# apt-get install pkg-config`)...
```
...
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for …
```

pkg-config also needed?

---

mod/stateful/Makefile
mod/stateless/Makefile

Small change that helps a lot in automated cross-compiling tasks.

Please allow us to set Makefile variables from outside

---

usr/configure.ac

Fixes breakage of build on systems using alternative libc in their toolchain, e.g. LEDE/OpenWRT

added AC_SEARCH_LIBS for argp

---

usr/README

If pkg-config isn't installed, then the configure script can't find the netlink dependency. That confused me since i did have the latest version of nl installed.
the error message looks like this:
checking for LIBNLGENL3... no
configure: error: in `/root/jool/Jool-3.5.2/usr':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.
Alternatively, you may set the environment variables LIBNLGENL3_CFLAGS
and LIBNLGENL3_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Added documentation that pkg-config is also needed

---

mod/stateful/bib/db.c

Only `db->tcp.log_bibs` was being set. Also set `db->udp.log_bibs` and `db->icmp.log_bibs`.

Sync UDP and ICMP logging with TCP

---

src/mod/nat64/bib/db.c

A pair of logging functions in src/mod/nat64/bib/db.c were using 'time_to_tm()' which was removed in 4.20.0.
This patch updates those calls to 'time64_to_tm()', and also updates the related calls to the deprecated 'do_gettimeofday()' to use 'ktime_get_real_seconds()' instead.

Fix compile of 3.6.0-rc3 against kernel 4.20.x

---

src/usr/iptables/common.c

Should use leading space instead of trailing space,  or JOOL options will be wrongly concatenated
with previous options like below:
```
root@buster:~# ip6tables -t mangle -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
JOOL       all      ::/0                 2408:8207:2472:2f70::/96 instance: default 
JOOL       udp      ::/0                 2408:8207:2472:2f70::/96  udp dpts:61001:65535instance: default
root@buster:~# iptables -t mangle -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
JOOL       icmp --  0.0.0.0/0            192.168.1.171       instance: default 
JOOL       tcp  --  0.0.0.0/0            192.168.1.171        tcp dpts:61001:65535instance: default 
JOOL       udp  -- …
```

properly print rule options with leading space

---

src/usr/iptables/common.c

A tiny patch to enhance https://github.com/NICMx/Jool/pull/299.
According to convention of standard iptables extensions, there shouldn't be space
between rule option name and value.

follow iptables rule option format convention

---

docs/en/install.md

Without libtool, `autogen.sh` fails:
```
$ ./autogen.sh 
aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
configure.ac:10: installing './compile'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
src/usr/argp/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
src/usr/argp/Makefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/usr/argp/Makefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/usr/argp/Makefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
src/usr/argp/Makefile.am:1:   its definition is in aclocal's search path.
src/usr/argp/Makefile.am: installing './depcomp'
src/usr/nl/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined …
```

add build dependency "libtool" for build from git repository

---

docs/en/alpine-linux.md
docs/en/documentation.md

Note: Alpine v3.11 will be released in few weeks. However, the packages are already available in the edge repositories.

Add documentation for Alpine Linux

---

docs/en/usr-flags-stats.md

- Explain about the new jool-exporter being available
- Keep generic + link to projects README
- State that it's not maintained by Jool core developers
Fixes #348

Add a time series stats section to stats documentation

---

src/common/config.h
src/mod/common/joold.c
src/mod/common/nl/nl_common.c
src/usr/nl/core.c

This is a mostly cosmetic change, based on the discussions in #340 and comments on 58bf14e. This moves the header magic so that it's defined in one place only, so that if its content or length changes in the future all consumers of the header field will be updated automatically.

Define the netlink header magic string in the preprocessor

---

src/mod/common/db/pool4/rfc6056.c
src/mod/common/error_pool.c
src/mod/common/rfc7915/4to6.c
src/mod/common/rfc7915/6to4.c
src/mod/common/skbuff.c

See #379, I encountered a bunch of kernel module build failures on Fedora 35 with 5.17 kernels.
They are all in places where there was a placeholder 9999 specified for the `RHEL_MAJOR` in the kernel version check.
Since at least kernel 5.16 the underlying kernel patches (e.g. the renaming of `nf_reset` to `nf_reset_ct` etc.) are also present in the Fedora 35 & 36 kernels.
However the 5.16 series did not have `RHEL_RELEASE_CODE` and other RHEL_ veriables defined for whatever reason
and the `LINUX_VERSION_AT_LEAST`/`LINUX_VERSION_LOWER_THAN` conditional helpers handled them as "stock" kernels.
This made DKMS compilation still _work_.
The 5.17 kernels however do have `RHEL_RELEASE_CODE` defined again, thus the build fails because `RHEL_MAJOR` is 9, far from 9999.
Now the version checks are …

DKMS: Fix RHEL kernel version checks on 9.99 / 5.17

---

docs/en/config-atomic.md

As I mentioned Issue #388 , Jool configuration needs an appropriate pool4 entry corresponding to BIBs.
This PR adds the pool4 entry on the example configuration.

Fix the example configuration for NAT64

---

src/mod/common/nl/nl_common.c

Commit bffcc6882a "genetlink: remove userhdr from struct genl_info" caused the build to fail since the field no longer exists.
Replace with run-time calculation of the header offset.

fix: build on v6.6+ kernel

---

src/mod/common/compat_32_64.h
src/mod/common/nl/instance.c
src/mod/common/skbuff.c
src/mod/common/xlator.c

Hello!
I wanted NAT64 in custom Linux routers based on ARM926EJ-S, Cortex-A8, Cortex-A72, and Cortex-A53.
The first and the second architecture is 32bit so I have added the missing support for such.

Support 32bit architectures too
